/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Application */

#ifndef _Included_Application
#define _Included_Application
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Application
 * Method:    sayTschus
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Application_sayTschus
  (JNIEnv *, jclass);

/*
 * Class:     Application
 * Method:    autoConfig
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Application_autoConfig
  (JNIEnv *, jclass);

/*
 * Class:     Application
 * Method:    toggleSupply
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Application_toggleSupply
  (JNIEnv *, jclass, jint);

/*
 * Class:     Application
 * Method:    setOutputValue
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Application_setOutputValue
  (JNIEnv *, jclass, jint);

/*
 * Class:     Application
 * Method:    setVoltageSupply
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_Application_setVoltageSupply
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     Application
 * Method:    sayHallo
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_Application_sayHallo
  (JNIEnv *, jclass);

/*
 * Class:     Application
 * Method:    getInputValue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Application_getInputValue
  (JNIEnv *, jclass);

/*
 * Class:     Application
 * Method:    getOutputSetValue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Application_getOutputSetValue
  (JNIEnv *, jclass);

/*
 * Class:     Application
 * Method:    getVoltage
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_Application_getVoltage
  (JNIEnv *, jclass);

/*
 * Class:     Application
 * Method:    getCurrent
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_Application_getCurrent
  (JNIEnv *, jclass);

/*
 * Class:     Application
 * Method:    getNameSN
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Application_getNameSN
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
