/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Application_OpenL */

#ifndef _Included_Application_OpenL
#define _Included_Application_OpenL
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
