/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Application_OpenNewWindow */

#ifndef _Included_Application_OpenNewWindow
#define _Included_Application_OpenNewWindow
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
